### ISSUE TITLE
Support for Citus

### ISSUE THREAD

**Issue by thinknirmal** [powa-team/pg_qualstats#37]
Is there a known way of making this extension work for distributed tables on Citus? Currently it works flawless for regular tables, but stops tracking immediately after enabling distribution on a table.

Thank you.

**Comment by rjuju** [comment]
Hi @thinknirmal 

Are you saying to pg_qualstats entirely stops tracking new quals as soon as there's one table handled by citus, or that it stops tracking new quals only for the citus-enabled tables?

I think it's probably the 1st one, and it looks like citus' fault, as its code assume that citus is the only extension allowed on your server, since it doesn't take care of calling other extension hook as all other extensions should be doing.

Unless Citus documentation explicitly says that you cannot use any other extension if you want to use Citus, it's a bug that should be solved on their Citus.  That being said, they may do something incompatible with pg_qualstats, I'm not sure right now as I don't have any knowledge about this extension apart from checking how it's handling postgres hooks.

**Comment by rjuju** [comment]
I'm closing this issue as I didn't have any answer.  Feel free to reopen it if needed.
